### PR TITLE
Fix most annoying part of #8

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Backspace works now on my system. I can't think of a good reason for us
to be defining our own KEY_BS rather than using ncurses' KEY_BACKSPACE -
so let's stop doing that!

### CODE REVIEW

**Comment by FedeDP** [comment]
https://stackoverflow.com/questions/27200597/c-ncurses-key-backspace-not-working
I needed that change because on my system KEY_BACKSPACE is not properly caught.
Can you update PR keeping both? Thanks!

**Comment by ctrlcctrlv** [comment]
How should I do that? Just simple 

```
case KEY_BS:
case KEY_BACKSPACE:
```

?

What if `127` maps to something else on another system? Then no one will be able to input that key. I think it would be better for you to figure out why your terminal emulator isn't handling this properly, you might be missing a terminfo file, or using the wrong one.

**Comment by FedeDP** [comment]
I'll have a look, thanks for the hint!

**Comment by ctrlcctrlv** [comment]
Sure :) If I knew your terminal emulator I could give you more help; for example I use `termite`, which requires its own terminfo file. Sometimes doing `export TERM=xterm-256color` can solve problems like these, because most terminal emulators are xterm-256color compatible, but it's always better to be using the correct termcap file with the same name as `$TERM`.

**Comment by FedeDP** [comment]
I'm using konsole, infocmp shows this: http://dpaste.com/0S9Z810.
Moreover, from here: http://comp.unix.programmer.narkive.com/GTteX1j1/ncurses-backspace#post3:

> For many terminals, ^? is the code that indicates the backspace
> key. For others, it is ^H.
> 
> It sounds like your terminal is sending ^? but your terminal
> configuration is telling ncurses that your terminal will send ^H.
> It's possible that your TERM variable is set incorrectly, or perhaps
> you've unknowingly used stty(1) to change your terminal configuration.
> 
> Because both of these codes (^? and ^H) are so commonly associated
> with the backspace key in the Unix, a lot of terminal software is
> hacked to accept either key as backspace, regardless of the actual
> configuration. The result of this fact is that people will have their
> backspace key misconfigured and won't know it until they test some
> software that they've written themselves.


What do you think? Should be support both or force KEY_BACKSPACE?

**Comment by ctrlcctrlv** [comment]
I think we should force `KEY_BACKSPACE` because encouraging people to do the wrong thing by making it easier for them to do so is itself wrong, and we could refer to this issue if anyone else asks.

But if you insist on hacking `127` in I can edit my PR to do so.

**Comment by FedeDP** [comment]
For me it's ok to only support BACKSPACE.
Can you update the pr rebasing on current master too? :)

**Comment by ctrlcctrlv** [comment]
Rebased 😄

**Pull request merged**
